### ISSUE TITLE
Feature Request: Make Spectator not reset the game.

### ISSUE THREAD

**Issue by Paxtez** [RossenX/NullDC-BEAR#14]
It appears that trying to spectate a room resets the game of the people playing.  It would be nice if that didn't happen.

I'm guessing syncing is the problem.  But maybe when a bear gets a request to spectate it creates a save state, transmits that, then starts sending over the reply data to catch up the spectator?

Awesome program BTW!

**Comment by RossenX** [comment]
I'm not sure what you mean, because spectating does not reset the game of the people that are playing. HOWEVER there are no savestates in nulldc so spectators have to watch the session from the start.
The way it works is bassicly when someone asks to spectate a player, the player will send over the VMU/System Menu data that are saved in the start of every session to the spectator. Then it sends over the input data from the start at 120FPS (until it catches up of course) So i think maybe you're just misunderstanding the spectator system it starts from the start of the session but the people playing the game are not affected at all.

**Comment by Paxtez** [comment]
Ahh, that makes sense.  That didn't occur to me, I watched a few people and it looked like it started from the beginning.  I just assumed I was watching it live. I guess I didn't even realize it was playing back faster.

I suppose having options to do playback at 1x so you can watch it back as normal, or as fast as possible to get closer to live might be useful.

I was thinking a save state might be a good way to catch up right away.  But I guess NullDC doesn't have save states, so that might be harder.

I'll close this.  Thank you for clearifying!
