### ISSUE TITLE
Nulldc error, please help!

### ISSUE THREAD

**Issue by OTKhsh** [RossenX/NullDC-BEAR#25]
Hello, and I noticed a problem with nulldc after the update. After the update, some of my games don’t work. Like my account was deleted, all my games were gone, cvs2 stopped working. It said that this games is not accepted by the motherboard. This is the first time it’s ever happens, and I wonder if you can fix it in the next update. Please consider.

**Comment by RossenX** [comment]
Did you use to start it from the windows10 search bar? They changed something with that search bar and it would change reference to where the app it started was. Try starting it from the actual EXE or a shortcut of nulldc.bear.exe and not through the windows 10 search bar. 
Also if it's on an external hard drive that can cause that error sometimes.
What path is your nulldc.bear.exe in?

**Comment by OTKhsh** [comment]
The way I opened nulldc was from my files at first, and then when I tried to open it from my files after the update, it says I have to put it in a new folder.

**Comment by RossenX** [comment]
Oh yeah the new one will not let you install or start inthe downloads folder. so if you have itin there it'll tell you to move it.
You can move the the whole folder anywhere and should be fine, unless you did not make a folder for it and it's just lose files inyour downloads folder(which is why i don't allow that anymore, having lose files in your downloads folder can cause all kinda issues). you can copy over your roms from the downloads folder where bear was to the new one.
Naomi is inthe 'roms' folder, dreamacst is in the dc/roms folder and mednafen(all other systems) is in the medanfen/roms folder.
