### ISSUE TITLE
No Rollback Netcode!

### ISSUE THREAD

**Issue by Bailey-Rudolph** [RossenX/NullDC-BEAR#28]
Rollback is the **FUTURE**. NullDC Bear is a great way to play old-school video games with friends, but it is missing the game-changing networking solution to playing games online with people across the world. Please consider working on a branch that has [GGPO ](https://www.ggpo.net) so that others can fork it and try to help provide rollback so that we can all play games online as if they were offline.

**Comment by RossenX** [comment]
Thank you! and of course i'm looking into rollback and all that's like the Ultimate goal, delay based was used because it's easy to setup and works on pretty much everything with very little data needed.

GGPO is amazing and i know all about it and how it works the main issue is that save-states for Naomi/Dreamcast are quite big and slow and GGPO requires a save-state every frame and to be able to rollback seemlessly requires the loading or states to also be very optimized. Right now that's pretty hard to do with how big the states are and it's emulation-wise code since we do not have the source code or anything for the original games like Slippy had for Smash. GGPO (or any other Rollback method) is actively being worked on and investigated don't worry about that, it's just going to take time to figure out how to do it and make it actually work without putting your FPS to like 1(or less)
