### ISSUE TITLE
Nulldc BEAR disable 4 player mode no matter what i do!

### ISSUE THREAD

**Issue by pftmclub** [RossenX/NullDC-BEAR#31]
Hello, somehow everytime i launch a NES game, it's disable Famicom 4-player adapter by default. I relaunch again thought BEAR launcher, it's keep happening the same result. The only way to fix it is launch the game via Mednafen Command Line.

I hope you can resolve this problem on next version

**Comment by RossenX** [comment]
When you launch a game through BEAR do you set the multi-tap option?
![Screenshot_1](https://user-images.githubusercontent.com/11183420/120939241-c94b4900-c71f-11eb-97b4-20c7954e0650.png)

**Comment by pftmclub** [comment]
> When you launch a game through BEAR do you set the multi-tap option?
> ![Screenshot_1](https://user-images.githubusercontent.com/11183420/120939241-c94b4900-c71f-11eb-97b4-20c7954e0650.png)
> 
> I'm pretty sure that by default mednafen does not require anything to use the four score plugin, it's always on by default. Which game are you trying to play?

"Nekketsu! Street Basket: Ganbare Dunk Heroes " 

What i mean is "nes.input.fcexp" value always set to "none" after i launch a game.  I have to manual config it to "4player"

**Comment by RossenX** [comment]
Ohh i got you now the famicom expansion port, i was thinking about the four score adapter. Gotchu i'll add an extra option in the mednafen configs for the expansion port. Right now it's setting itself to 'none' probably because 'nes.input.*" are set to none if they are not the ones specified in the BEAR configs and we there is no entry for the expansion port, i'll add one for it in the next update, thanks for letting me know!
