### ISSUE TITLE
Feature Request:  Add selected delay for challenge pop-up.

### ISSUE THREAD

**Issue by Paxtez** [RossenX/NullDC-BEAR#32]
It would be really useful if the "Here comes a new Challenger" Pop-up had the delay selected by the host.
Currently it only shows the suggested delay, but not what the person selected.
(I am using the MVC2 theme if it matters)

Semi related: The suggested delay will often be 0.something for close people.   Since 0 is never "recommended" shouldn't the suggested delay be "1" if the Ping/FPS is less than 1?

**Comment by RossenX** [comment]
Suggested delay is only 0 if you cannot ping the person you're fighting and so the system has no idea wtf to set it to.
The defauly 'minimum' delay is set to 2, because 0 and 1 is super hard to do online. I seen some people use 1 but 0 is pretty much impossible for online but it can be done in lan or if you somehow have less than 16ms(Probably less since some of those 16ms need to be used to render the frame) consistently with someone online.

Though that's a good idea i can have it show what the delay the host set to on the screen waiting for host screen.
