### ISSUE TITLE
Rollback Netcode

### ISSUE THREAD

**Issue by EmmaMagneto** [RossenX/NullDC-BEAR#34]
Just asking, Is there any possibility to add this feature?
People are taking this emulator seriusly and it has been used for tournaments along the pandemics.

btw, ty!

**Comment by RossenX** [comment]
Heyo! Sorry for the late reply literally totally missed this question. (Discord usually best way to get answers)

Rollback is the ultimate goal and is bejng looked into and experimented with it’s just a pain to do because it’s states are top big to be smooth unlike older smaller emulators and adding rollback retroactively is always annoying. Definitely being looked into though i can say that much not sure about how it’ll end ip.
