### ISSUE TITLE
Can't Use NullDC

### ISSUE THREAD

**Issue by sincrediblekay** [RossenX/NullDC-BEAR#35]
So after I put nullDC into an empty folder, it stops unpacking files and gives me an error message. It says I can't run the application because it's path to the Release No Trace file isn't accessible. The Release No Trace File is in the same location as nullDC itself. But, anytime I try and move the Release No Trace to the dc folder, it won't allow me to do so either, as it says I don't have permission. Don't know if I'm just PC illiterate or what, but I appear to be the only person having this issue.

**Comment by RossenX** [comment]
Hey there, well that sounds annoying. A few things i can think that might cause something like this.
1. You put BEAR in a protected windows folder so it won’t let you do stuff in there automaticlly for security reasons. Try Making a folder on the desktop or something always works. I have mine in D:/games/bear as long as it’s not in some system folder.
2. You do not have admin rights on that pc so BEAR can’t finish extracting and making all the folders. You would need a account on that pc with admin rights to fix this one.
3. You antivirus is blocking BEAR from extracting everything because sometimes the “AI” based antivirus think it’s suspicious for a program to unpack other programs from itself. If this is the case add the BEAR folder to exceptions in your anti corus software.

**Comment by sincrediblekay** [comment]
I tried the first solution. It appears to have worked so far. Thank you for you quick response, I appreciate it.
