### ISSUE TITLE
NullDC Bear System.Net Error

### ISSUE THREAD

**Issue by SoulSolid95** [RossenX/NullDC-BEAR#38]
Hi RossenX, I just installed NullDC Bear with Radmin to play some MvC2 online, after setting everything up, it worked perfectly fine, but while in training mode I wanted to change some controls, so I did then Bear stopped working and froze, I closed it and now everytime I try to reopen NullDC Bear I get this message:
![crashy](https://user-images.githubusercontent.com/89103758/129792062-e523260e-720e-4510-adb6-f32a0636827f.png)

Please let me know if you need any more details, keep up the awesome work! :)

**Comment by SoulSolid95** [comment]
Edit: After restarting my pc the issue was gone, I went in to test my controller out again and while changing controls through NullDC Bear It froze while saving again, so I killed it and upon reopening the program I got this error again. Im really confused as so what is happening and why I have to restart for this error to go away.

**Comment by RossenX** [comment]
That error says that the socket is already being used. So the port that BEAR uses 8002 is being used by something else. Or if you have two instances of BEAR open on the same PC that'll cause that also but usually you cannot open two instances of BEAR on the same PC.

Try this out. Restart your PC and go into controls advanced->reset all.
Then change your controls however you like and when saving even if it freezes just give it a min or two. Maybe the config writing is being very slow for some reason. I know one person had a similar issue that the configs would take very long to write for some reason was caused by their keyboard brand or something. So give it a min or two to save your settings maybe that'll do it.

**Comment by SoulSolid95** [comment]
It only ever happens when I force quit the app when it freezes (more notably: when it freezes while saving control config). It might be a noteworthy bug report also that when I open controller config more than once per session it freezes the entire program which would lead to the Socket Error. Ill try what you recommended and Ill get back to you.

**Comment by SoulSolid95** [comment]
Tried out your suggestion, It didnt really change much but Its fine it only happens when changing controls and Im done configuring so I wont be needing to open the setting again. Thanks though!
